# Blog info
blog_name: Senorui
slogan:  Be a charming badass, kind but not happy.
url: https://senorui.top/

# Set avatar (Absolute url and relative url)
avatar: /img/home/avatar.webp

# rss
rss: /atom.xml

# Set favicon
favicon: /icon/favicon.ico

# For seo
keywords: ç¿å…ˆæ£®,åšå®¢,Senorui,hexo,é™æ€ç½‘ç«™,å­¦ä¹ åˆ†äº«

home_nav:
  - name: æ–‡æ¡£
    icon: fa fa-home
    url: /archives/
    target_blank: false #ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: é¡¹ç›®
    icon: fa fa-code
    url: /project/
    target_blank: false 
  - name: å¯¼èˆª
    icon: fa fa-paper-plane
    url: https://nav.senorui.top/
    target_blank: true #åœ¨æ–°é¡µé¢æ‰“å¼€     
  - name: éŸ³ä¹
    icon: fa fa-music
    url: https://music.senorui.top/
    target_blank: true 
  - name: å¼€å¾€
    icon: fa fa-subway
    url: https://travellings.now.sh/
    target_blank: true    
  - name: å…³äº
    icon: fa fa-address-card
    url: /about/
    target_blank: false

# config page nav
page_nav:
  - name: æ–‡æ¡£
    url: /archives/
    target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åˆ†ç±»
    url: /category/
    target_blank: false
  - name: æ ‡ç­¾
    url: /tag/
    target_blank: false 
  - name: å‹é“¾
    url: /link/
    target_blank: false
  - name: å…³äº
    url: /about/
    target_blank: false
  - name: æœç´¢
    url: /search/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# é¢åŒ…å±‘
breadcrumb:
  isShow: true # true|false

# ç›’å­
toolbox:
  isShow: true # true|false
  text: èœå•

search_slogan:
  isShow: true # true|false
  text: å¯ä»¥åœ¨è¿™é‡Œæœç´¢æœ¬ç«™å†…å®¹å“¦ï¼

link_slogan:
  isShow: true # true|false
  text: æ¬¢è¿äº¤æ¢å‹é“¾ï¼äº¤æ¢å‹é“¾è¯·å‘é‚®ä»¶åˆ° info@senorui.com

link_info:
  isShow: true # true|false
  text: æœ¬ç«™ä¿¡æ¯è§æœ€æœ«å‹é“¾ï¼Œå› é˜²ç›—é“¾ç‰¹éº»çƒ¦å¤§å®¶åœ¨æ­¤å³é”®å¤åˆ¶å›¾ç‰‡åœ°å€ã€‚

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  diary: true
  link: true
  about: false

donation:
  show: true
  btn_text: æ”¯æŒä¸€ä¸‹
  tip: æ¬¢è¿å’ŒSenoruiè¿›è¡ŒPYäº¤æ˜“ğŸ˜ï¼
  items:
    - type: å¾®ä¿¡
      text: å¾®ä¿¡æ‰«ä¸€æ‰«
      imgUrl: /img/home/qr-wechat.webp
    - type: æ”¯ä»˜å®
      text: æ”¯ä»˜å®æ‰«ä¸€æ‰«
      imgUrl: /img/home/qr-alipay.webp


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# æ–‡ç« ç‰ˆæƒå£°æ˜
post_copyright:
  isShow: true   # true|false  

# =========================================================
# ä¸ªæ€§åŒ–è®¾ç½®
# =========================================================

# Custom CSS style, æ¨èæŠŠæ ·å¼æ–‡ä»¶æ”¾åœ¨blogæºç æ–‡ä»¶å¤¹ï¼Œè€Œä¸æ˜¯ä¸»é¢˜é‡Œé¢
personal_style: /css/personal.css

# è¿™ä¸ªå€¼å–å†³äºä½ å¾—é¦–é¡µèƒŒæ™¯å›¾ç‰‡æ˜¯æ·±è‰²è¿˜æ˜¯æµ…è‰²ï¼Œæ·±è‰²ç”¨darkï¼Œæµ…è‰²ç”¨light
# home_background_scheme: light # darkã€light
# å·²ç»å¼ƒç”¨ï¼Œæ·±è‰²æ¨¡å¼ä¸‹ä¼šè‡ªåŠ¨åˆ‡æ¢


# custom font-family æš‚æ—¶åªæ”¯æŒè¿™3ç§è‹±æ–‡å­—ä½“ï¼Œä½ å¯ä»¥å®Œå…¨è‡ªå®šä¹‰å­—ä½“(çœ‹æ–‡æ¡£)
blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: Lobster-Regular,PoiretOne-Regular,Linux Biolinum

# é¦–é¡µæ˜¾ç¤ºçš„æ˜¯å¯¼èˆªè¿˜æ˜¯æ–‡ç« å½’æ¡£
init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# ç¬¬ä¸‰æ–¹æœåŠ¡
# =========================================================

# ä¸­å›½å¤©æ°”ç½‘æ’ä»¶ï¼šhttps://cj.weather.com.cn/plugin/simple
# å’Œé£å¤©æ°”æ’ä»¶ï¼šhttps://widget.qweather.com/create-simple
# é»˜è®¤å’Œé£æ’ä»¶ï¼Œè‹¥è¦æ›´æ¢è®°å¾—ä¿®æ”¹æ’ä»¶DIVçš„idå’Œapiåœ°å€ã€‚
mywth:
  isopen: true       # true|false
  key: xxxxxxx    # ä½ çš„å¤©æ°”æ’ä»¶key

# ä»Šæ—¥è¯—è¯API
jinrishici:
  isopen: true       # true|false

# é¦–é¡µfoot 
foot:
  isopen: true  # true|false
  webdate: 2018-2021    # ä½ çš„å»ºç«™æ—¶é—´
  icp: æ»‡ICPå¤‡20005709å·  # ä½ çš„ICPå¤‡æ¡ˆå·
  gicp: æ»‡å…¬ç½‘å®‰å¤‡53011402000463å·  # ä½ çš„å…¬ç½‘å®‰å¤‡æ¡ˆå·
  gicp_url: https://4m.cn/U6Xy9      # ä½ çš„å…¬ç½‘å®‰å¤‡ç½‘å€

# pwa
pwa:
  isopen: true                    # true|false
  manifest: /site.webmanifest     # manifest urlï¼Œéœ€è¦æ ¹æ®å®é™…ä¿®æ”¹site.webmanifestæ–‡ä»¶å¹¶æ”¾åœ¨åšå®¢æ ¹ç›®å½•ä¸‹
  name: ç¿å…ˆæ£®                    # pwa name
  background_color: abd7ff        # pwa background color, not need "#"
  theme_color: abd7ff             # pwa theme color, not need "#"

# å¼€å¯mathjaxæ”¯æŒï¼Œè‹¥éœ€è¦åˆ™å¼€å¯å¦åˆ™å»ºè®®å…³é—­
mathjax:
  isopen: false  # true|false
  cdn: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# ç™¾åº¦ç»Ÿè®¡
baidu_analytics:
  isopen: false  # true|false
  id: xxxxxxxxxxxxx   # ç™¾åº¦ç»Ÿè®¡ID

# ä¸è’œå­ç»Ÿè®¡
busuanzi: true   # true|false

# Comment service


# =========================================================
# é¡µé¢å†…å®¹è®¾ç½®
# =========================================================

about:
  - type: web
    icon: icon-home
    text_value:
    - "æœ¬ç«™ç”±Hexoé©±åŠ¨."
    - "åä¸ºäº‘æä¾›é™æ€å­˜å‚¨ä¸åŠ é€ŸæœåŠ¡."
    - "æœ¬ç«™ç”¨äºè®°å½•ä¸ªäººç”Ÿæ´»ä¸­çš„æ‰€å­¦ã€æ‰€æ€å’Œæ‰€æ‚Ÿ."
    - "æ ¹æ®ç›¸å…³æ³•å¾‹æ³•è§„ï¼Œæœ¬ç«™ä¸å¯¹æ¬§ç›Ÿç”¨æˆ·æä¾›æœåŠ¡."
  - type: me
    icon: icon-user
    text_value:
    - "Marchï¼Œ1998ï¼ŒSpring."
    - "å–œæ¬¢æ¢ç´¢ï¼Œå–œæ¬¢çæï¼Œæ“…é•¿ç¡æ‡’è§‰."
    - "éè®¡ç®—æœºä¸“ä¸šçš„å°ç™½ä¸€æšï¼Œå–œæ¬¢æ¢ç´¢è®¡ç®—æœºé¢†åŸŸï¼Œç„¶å¹¶åµ."
    - "æ›¾ç»æ¢¦æƒ³å¾æœæ˜Ÿè¾°å¤§æµ·ï¼Œåæ¥å´å‘ç°è‡ªå·±åªæ˜¯å˜æˆäº†ä¸€é¢—ç¹æ˜Ÿ."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@Senorui"
    text_value_url: https://github.com/Senorui
  - type: QQ
    icon: icon-qq
    text_key: Chat to
    text_value: "@Senorui"
    text_value_url: /qq.html
  - type: Email
    icon: icon-mail
    text_key: Email To
    text_value: "@Senorui"
    text_value_url: https://mailhide.io/zh/e/SttMQ6mq
  - type: location
    icon: icon-location
    text_value: ä¸­å›½ Â· æ˜†æ˜
  - type: web
    icon: icon-info-with-circle
    text_key: æœ¬ç«™çš„
    text_value: "@éšç§å£°æ˜"
    text_value_url: /about/privacy-policy.html
  - type: web
    icon: icon-feather
    text_key: æœ¬ç«™çš„
    text_value: "@è®¿é—®ç»Ÿè®¡"
    text_value_url: https://tongji.baidu.com/web/welcome/ico?s=45d43774ea060c954e384c4d3a6b66e1

link:
  - name: Sanarous's Blog
    info: Dream it possible, make it possible
    url: https://bestzuo.cn/
    avatar: /img/friends/Sanarous.webp
  - name: ç¿å…ˆæ£®
    info: Be a charming badass, kind but not happy.
    url: https://senorui.top/
    avatar: https://s3.ax1x.com/2020/12/29/rqEtzj.png

  #- name: 
  #  info: 
  #  url: 
  #  avatar: /images/friends/.png

project:
  - type: personal
    name: API
    url: https://api.senorui.top/
    intro: A self-use random image API.
  - type: personal
    name: Fexo
    url: https://github.com/Senorui/fexo
    intro: A minimalist design theme for hexo.
  - type: personal
    name: Vitreous
    url: https://github.com/Senorui/Vitreous
    intro: A transparent style navigation homepage.
  - type: personal
    name: Music player
    url: https://github.com/Senorui/music
    intro: A translucent and textured music player.

#  - type: personal
#    name: 
#    url: 
#    intro: 